"""Initial schema

Revision ID: daef80fbb2ff
Revises: 
Create Date: 2026-08-04 20:19:26.658577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daef80fbb2ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_reserve', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('born_at', sa.DateTime(), nullable=False),
    sa.Column('died_at', sa.DateTime(), nullable=True),
    sa.Column('cause_of_death', sa.Text(), nullable=True),
    sa.Column('last_income_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_state',
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_set_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('kill_switch')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('cycle_at', sa.DateTime(), nullable=False),
    sa.Column('situation_snapshot', sa.JSON(), nullable=False),
    sa.Column('chosen_channel', sa.String(), nullable=True),
    sa.Column('plan_text', sa.Text(), nullable=False),
    sa.Column('legality_justification', sa.Text(), nullable=False),
    sa.Column('net_result', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_deducted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['chosen_channel'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boss_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_agent_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.drop_table('boss_notes')
    op.drop_table('agent_logs')
    op.drop_table('system_state')
    op.drop_table('channels')
    op.drop_table('agents')
    # ### end Alembic commands ###
